name = "edcloudwasm"
main = "_worker.js"  # 你的 JS 逻辑代码
compatibility_date = "2026-05-02"

# pages中环境变量需要手动填写并重试部署才会生效，worker环境变量和路由自定义域名这些建议直接使用wrangler.toml文件来配置
# --- worker环境变量配置 ---
[vars]
# VLESS 的 UUID
UUID = "637f06d1-e2f8-4bb1-a93c-403e9cd71355"
# Trojan 的密码
PASSWORD = "637f06d1-e2f8-4bb1-a93c-403e9cd71355"
# SS使用aes128gcm加密的密码
SSPASS = "637f06d1-e2f8-4bb1-a93c-403e9cd71355"
# S5和HTTP 入站验证用户名 
S5HTTPUSER = "mtfxyn"
# S5和HTTP入站验证密码
S5HTTPPASS = "Zhuyuzheng2009"


[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true
